### ISSUE TITLE
Is this dokerized_fbctf the official download of the repo or it is your clone?

### ISSUE THREAD

**Issue by uppusaikiran** [qazbnm456/dockerized_fbctf#1]
I tried installing it with steps given by you and it indicated that it is 200MB + ,but the official image from fbctf is less that that.Are you implementing from official source or any changes were made>

**Comment by qazbnm456** [comment]
@uppusaikiran You may want to look into this [thread](https://github.com/docker/hub-feedback/issues/331).

**Comment by uppusaikiran** [comment]
What i was asking was is this project created by you @qazbnm456  is compatible with the official facebook open source project

**Comment by qazbnm456** [comment]
Yes, it's compatible with the official facebook open source project. What this repo does is just git clone fbctf and run provision script as fbctf's README said.

**Comment by uppusaikiran** [comment]
`
ubuntu@sai:~/dockerized_fbctf$ docker run -p 80:80 -p 443:443 --rm dockerized_fbctf
FATA[0000] Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS? 
ubuntu@sai:~/dockerized_fbctf$ sudo docker run -p 80:80 -p 443:443 --rm dockerized_fbctf
[sudo] password for ubuntu: 
Unable to find image 'dockerized_fbctf:latest' locally
Pulling repository dockerized_fbctf
FATA[0023] Error: image library/dockerized_fbctf:latest not found 
ubuntu@sai:~/dockerized_fbctf$ ls
config.sh   http_fbctf.conf   import_empty_db.sh  service_startup.sh
Dockerfile  https_fbctf.conf  README.md           setup_lets_encrypt.sh
ubuntu@sai:~/dockerized_fbctf$ cd ..
ubuntu@sai:~$ docker run -p 80:80 -p 443:443 --rm dockerized_fbctf
FATA[0000] Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS? 
ubuntu@sai:~$ sudo docker run -p 80:80 -p 443:443 --rm dockerized_fbctf
Unable to find image 'dockerized_fbctf:latest' locally
Pulling repository dockerized_fbctf
FATA[0024] Error: image library/dockerized_fbctf:latest not found 

`

**Comment by uppusaikiran** [comment]
Can you rectify this error Unable to find image 'dockerized_fbctf:latest' locally

**Comment by uppusaikiran** [comment]
@qazbnm456  I have downloaded the entire source code when i executed the command
`docker run -p 80:80 -p 443:443 --rm dockerized_fbctf`
It is telling **Unable to find image 'dockerized_fbctf:latest' locally**

**Comment by qazbnm456** [comment]
@uppusaikiran Do you build the image by your own? If you follow README to build your own image, you can find it through `docker images`, or you can just `docker pull qazbnm456/dockerized_fbctf` to get it from Docker hub without downloading entire source code here.

**Comment by uppusaikiran** [comment]
How to rectify this error and everything is perfect in pulling.Thanks @qazbnm456 

```
root@sai:/home/ubuntu# docker run -p 80:80 -p 443:443 --rm qazbnm456/dockerized_fbctf
FATA[0001] Error response from daemon: Cannot start container 458ba6d2f439e021a733aa5c73457738ff434ed8f2a32283d9321901da2276fd: Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use 
root@sai:/home/ubuntu# docker run -p 80:80 -p 4430:4430 --rm qazbnm456/dockerized_fbctf
FATA[0000] Error response from daemon: Cannot start container 6566ef565f37d7d7b668315b963b09a349b7e0ed3bccd59376ece5ce89a8ae54: Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
```

**Comment by uppusaikiran** [comment]
```
root@sai:/home/ubuntu# netstat -pna | grep 443
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      5253/nginx      
tcp        1      0 192.168.235.136:49771   162.213.33.50:443       CLOSE_WAIT  5471/unity-scope-ho

```

**Comment by qazbnm456** [comment]
Because the program is using port 443, you should change the binding port 443 to another, such as `docker -p 80:80 -p 10443:443 --rm qazbnm456/dockerized_fbctf`. Then, you can browse https://localhost:10443 to check if it's okay.

**Comment by uppusaikiran** [comment]
![screenshot 27](https://cloud.githubusercontent.com/assets/9650342/15267839/baa1e87e-19ea-11e6-9108-7fb70de4bda6.png)
Working perfectly fine .You did great job.

**Comment by qazbnm456** [comment]
@uppusaikiran Thanks. It's great to see you finally deploy fbctf, which is the main goal of this repo to let anyone deploy fbctf more easily. :) I'm closing the issue now,  and feel free to re-open if you still need help. :)
