### ISSUE TITLE
Cannot Start Server 

### ISSUE THREAD

**Issue by SimplyPrez** [qazbnm456/dockerized_fbctf#2]
Pulled docker image and tried to run server and got error:
`FATA[0001] Error response from daemon: Cannot start container 4a3887ba209c4b2883d25f5f11a5b05e007ac2bf6a2e67c54f071c73c80246e2: [8] System error: exec format error `

**Comment by qazbnm456** [comment]
I've tested both latest and multi_containers tags on my OS X EL Capitan and ubuntu 14.04 LTS, and they are both running without any issue. Would you mind provide your system infos? I suspect it's some kind of architecture problem like [this thread](https://github.com/docker/docker/issues/10668) has discussed.

**Comment by SimplyPrez** [comment]
I've tried it both on a Xubuntu 15.04 and Ubuntu 14.04 VM virtualbox with the same error on both system. I've read the post but not sure where I'm suppose to add a shebang.

**Comment by qazbnm456** [comment]
Are your machines running 64-bit OS? Could you provide detailed system infos  as attachment? Thanks!

**Comment by SimplyPrez** [comment]
Ok VM Ubuntu was 32 bit and is now working.As soon as i get back on the Xubuntu computer i will send you system info and check if it is 32 bit.

**Comment by drone789** [comment]
hi qazbnm456:

      mysql can not startup. Maybe what's the problem.

realm@ubuntu:~$ sudo docker run -p 80:80 -p 443:443 --rm qazbnm456/dockerized_fbctf
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/02_service_startup.sh...
 * Restarting nginx nginx
   ...done.
 * Starting MySQL database server mysqld
   ...fail!
*** /etc/my_init.d/02_service_startup.sh failed with status 1

*** Killing all processes...
realm@ubuntu:~$ uname -a
Linux ubuntu 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by qazbnm456** [comment]
@SimplyPrez Okay!

@drone789 Could you type `sudo docker run -p 80:80 -p 443:443 -it --rm qazbnm456/dockerized_fbctf /bin/bash` to enter the container, then `service mysql start` to see if it's working or not. If it's not working properly, could you then paste the error messages here? Thank you for your comments btw.

**Comment by drone789** [comment]
@qazbnm456 
realm@ubuntu:~$ sudo docker run -p 80:80 -p 443:443 -it --rm qazbnm456/dockerized_fbctf /bin/bash
[sudo] password for realm: 
root@86e3782adacb:~/fbctf# service mysql start
 * Starting MySQL database server mysqld                                                                                                
                                                                                                                                 [fail]
root@86e3782adacb:~/fbctf# 
root@86e3782adacb:~/fbctf# netstat -antlp | grep mysql
root@86e3782adacb:~/fbctf# netstat -antl              
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
root@86e3782adacb:~/fbctf#

**Comment by qazbnm456** [comment]
@drone789 Is your image the latest build? Did you run on your host or on VM? Have you ever tried to reinstall mysql-server again in container? It seems no other issues related to cause such problem.

Once you find out any other error logs or something helpful things, please paste here, thanks :)

**Comment by SimplyPrez** [comment]
@qazbnm456 Ok the cpu of the Xubuntu computer was 32bit so yah thanks for you help anyway though!
