### ISSUE TITLE
443 port

### ISSUE THREAD

**Issue by whuben** [qazbnm456/dockerized_fbctf#3]
the following cmd will be more useful to run the docker (add the port 443->443 in contianer)
docker run --name fbctf -d \
    -p 10080:80 \
   -p 443:443 \
    --env MYSQL_USER=fbctf \
    --env MYSQL_PASSWORD=fbctf \
    --env MYSQL_PORT=3306 \
    --env MYSQL_DATABASE=fbctf \
    --env MEMCACHED_PORT=11211 \
    --link fbctf-memcached:memcached \
    --link fbctf-mysql:mysql \
    qazbnm456/dockerized_fbctf:multi_containers

**Comment by qazbnm456** [comment]
Hi @whuben, thanks for trying out, though this repo is not maintained for a while. 😕 

Now I'd recommend directly using the official [Dockerfile](https://github.com/facebook/fbctf/blob/master/Dockerfile) on [facebook/fbctf](https://github.com/facebook/fbctf). You may give it a try!
